name: Update README CLI 

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Update README Action
      uses: your-username/update-readme-cli-action@v1
      with:
        cli-path: './bin/cli.js'
